# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0002_auto_20170602_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField(default=0)),
                ('weapon_type', models.CharField(choices=[('M', 'Broń ręczna'), ('D', 'Broń zasięgowa'), ('A', 'Pancerz/Ubiór'), ('C', 'Użytkowy')], default='C', max_length=1)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
