# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0003_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='owned_by',
            field=models.ManyToManyField(to='character_sheet.Character_sheet'),
        ),
    ]
